def line():
    A = float(input("Ingrese el coeficiente A: "                                                          ))
    B = float(input("Ingrese el coeficiente B: "))
    X1 = float(input("Ingrese el coeficiente X1: "))
    X2 = float(input("Ingrese el coeficiente X2: "))
    print(f"El coeficiente A de su ecuación de la recta es: {float(A)}")
    print(f"El coeficiente B de su ecuación de la recta es: {float(B)}")
    print(f"El coeficiente X1 de su ecuación de la recta es: {float(X1)}")
    print(f"El coeficiente X2 de su ecuación de la recta es: {float(X2)}")
    print("")

    print("Para la siguiente ecuación:")
    print(f"\tY = {A}X + {float(B)}")
    print("")
    print("Dados los siguientes puntos:")
    print(f"\tP1 ({X1}, {(X1*A) + B})")
    print(f"\tP2 ({X2}, {(X2*A) + B})")
    Y1 = (X1*A + B)
    Y2 = (X2*A + B)
    print("")
    print(f"La distancia entre ellos es: {(((X2 - X1)**2) + (((Y2 - Y1)**2)))** 0.5}")
